로그인 기능을 구현
KTPT/Quna-client pull request #26
Opened 2021-01-25 14:59 UTC by toneyparky

resolve: #25 

---

간단하게 구현해봤습니다.

유효성 체크는 공백만 해두었습니다. 뭐가 더 있을거라 생각했는데 로그인은 공백 여부면 충분하더라구요. 추가적으로 검사할 내용 있다면 코멘트 부탁해요!

추가적으로 alert를 사용해서 메시지를 표시하는데 논의해보고 스낵바나 팝업을 라이브러리 사용해서 보여줘도 괜찮겠다 싶네요. 이야기해보죠!

### 저장된 토큰 사용법
~~~typescript
import {TOKEN} from '../../constants/token';

export const fetchAllQuestions = () =>
  axios.get("/questions", {
    headers: {
      Authorization: `Bearer ${localStorage.getItem(TOKEN)}`,
    },
  });
~~~

2021-01-26 11:01 UTC, kouz95 approved these changes
고생하셨습니다! 리뷰 확인해주세요~

2021-01-26 11:01 UTC, kouz95 commented on src/components/ApiButton.tsx
> +import {ParsedUrlQueryInput} from 'querystring';
사용하지 않는 것 같아요!

2021-01-26 11:01 UTC, kouz95 commented on src/pages/login/index.tsx
> +    if (input.nickname == null || input.nickname == '') {
`===` 을 사용하는게 좋을것 같아요

2021-01-26 11:01 UTC, kouz95 commented on src/pages/login/index.tsx
> +  const validate = (): boolean => {
return type을 규정해주는 이유가 따로 있을까요?

2021-01-26 11:01 UTC, kouz95 commented on src/pages/login/index.tsx
> +const Nickname = styled.div`
전 div에는 Container를 주로 붙이는 편인데 한번 같이 이야기 해보죠
```suggestion
const NicknameContainer = styled.div`
```

2021-01-26 11:02 UTC, kouz95 requested changes
고생하셨습니다! 리뷰 확인해주세요~

2021-01-26 11:13 UTC, kouz95 commented on src/pages/login/index.tsx
> +        router.push('/');
Link가 아니라 router를 쓴 이유가 있나요?

2021-01-26 11:15 UTC, kouz95 commented on src/pages/login/index.tsx
> +    if (input.password == null || input.password == '') {
35번 라인의 nickname과 password를 재사용해도 괜찮겠네요!

2021-01-27 08:39 UTC, toneyparky commented on src/pages/login/index.tsx
> +    if (input.nickname == null || input.nickname == '') {
좋은 포인트네요.
수정하겠습니다~

2021-01-27 08:40 UTC, toneyparky commented on src/components/ApiButton.tsx
> +import {ParsedUrlQueryInput} from 'querystring';
포매팅을 돌려야겠네요.
고맙습니다.

2021-01-27 08:44 UTC, toneyparky commented on src/pages/login/index.tsx
> +  const validate = (): boolean => {
typescript라서 적어봤습니다. boolean을 되돌려준다는 사실을 명시하자는 의미도 있네요. 
없어도 린트가 안 잡네요. 오호라.
보통은 리턴 타입을 적지 않는가용?

2021-01-27 08:44 UTC, toneyparky commented on src/pages/login/index.tsx
> +const Nickname = styled.div`
네 좋습니다😬

2021-01-27 08:45 UTC, toneyparky commented on src/pages/login/index.tsx
> +    if (input.password == null || input.password == '') {
그러게요.. 풀어놓고 사용을 잘 안했군요!

고맙습니다.

2021-01-27 08:46 UTC, toneyparky commented
좋은 코멘트들 감사합니다 경준님 :)
네이밍과 함수의 리턴타입에 대해서 곧 이야기해보죠~

2021-01-27 10:09 UTC, toneyparky commented on src/pages/login/index.tsx
> +const Nickname = styled.div`
NicknameContainer를 활용하기로 했습니다.

2021-01-27 10:19 UTC, kouz95 approved these changes
고생하셨습니다!

2021-01-27 10:19 UTC, merged